language: node_js
node_js:
  - "8"

sudo: required

services:
  - docker

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - docker build -t krzkowalczyk/angular-heroes .
