language: node_js
node_js:
  - "8"

sudo: required

services:
  - docker

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - docker build -t krzkowalczyk/angular-heroes .
